default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: shortener_development

test:
  <<: *default
  database: shortener_test

production:
  <<: *default
  database: shortener_production
  username: rails
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
